from multi_node_crl.utils.torch_utils import get_device
from multi_node_crl.utils.data_gen_utils import get_rand_A, rand_weight_matrix
from multi_node_crl.utils.eval_utils import compute_MCC, interventional_CRL